-- 可选 SQL 初始化（与 Prisma schema 对齐）
CREATE TABLE IF NOT EXISTS chat_sessions (
  id INT AUTO_INCREMENT PRIMARY KEY,
  sessionKey VARCHAR(191) UNIQUE NOT NULL,
  sourceSite VARCHAR(191) NOT NULL DEFAULT 'allctp.com',
  pagePath VARCHAR(191) NULL,
  country VARCHAR(191) NULL,
  visitorInfoJson JSON NULL,
  leadId INT NULL,
  status VARCHAR(50) NOT NULL DEFAULT 'AI_PROCESSING',
  createdAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3),
  updatedAt DATETIME(3) NOT NULL DEFAULT CURRENT_TIMESTAMP(3) ON UPDATE CURRENT_TIMESTAMP(3)
);
